### ISSUE TITLE
No refresh/rebuild after change chart settings

### ISSUE THREAD

**Issue by Delicate-aRt** [Zoomdata/edc-cratedb#2]
Chart is plotted only with default settings (scale, attributes to group etc). In case one change any settings (add filtering option, change grouping attribute, change time scale, update time range in time bar etc) - new chart won't be plotted.

Steps to reproduce:
1. Configure Crate.io data source
2. Add at least one chart for that data source
3. Open that chart
4. After chart is open and rendered try to change scale/add filters/change group att
5. New chart with new settings won't be plotted (only three continuously blinking three dots in left upper corner)

**Comment by bowenwr** [comment]
I don't think this has been an issue for awhile.

Cannot reproduce on latest Zoomdata and Crate connector, Crate version 1.0.1
