### ISSUE TITLE
Cannot get the EDC crate connector working with Zoomdata

### ISSUE THREAD

**Issue by kovrus** [Zoomdata/edc-cratedb#9]
edc-cratedb: master

Zoomdata v2.2.1, v2.3.1, v2.3.10
OS: Ubuntu 16.04 and CentOS 7
crate-jdbc: 1.13.1

The edc-crate connector is started as following:

```
 java -jar target/connector-server-cratedb-1.1.1-exec.jar
```
I am able to create the CrateDB data source in Zoomdata. But the exception
occurs when it is used to connect to CrateDB. The edc-crate connector logs
the following message:

```
WARN 51396 --- [tp1898220577-17] org.eclipse.jetty.http.HttpParser: bad HTTP parsed: 400 for HttpChannelOverHttp@3893657e{r=0,c=false,a=IDLE,uri=null}
```
and the connection validation fails.

I have tried to build the connector before this [commit](https://github.com/Zoomdata/edc-cratedb/commit/0a1f61c9858b4ae3895d22f64c97efa874e1ea26) and it works just perfectly.
It might be that this commit either breaks something or the readme does not
reflect the current state of the project.

**Comment by bowenwr** [comment]
This has been verified after the upgrade as not an issue. Thanks!
